name: agri_expert_app
description: A prototype Flutter app for Smart Crop Advisory System
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  geolocator: ^14.0.2
  http: ^1.6.0
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
